export const Type = {
    SET_USER: "SET_USER",
    ADD_TO_BASKET: "ADD_TO_BASKET",
    REMOVE_FROM_BASKET: "REMOVE_FROM_BASKET",
    UPDATE_QUANTITY: "UPDATE_QUANTITY",
    EMPTY_BASKET: "EMPTY_BASKET",
};